<?php
/**
 * Created by PhpStorm.
 * User: floatflower
 * Date: 2020/2/20
 * Time: 12:15 AM
 */

namespace App\Tests\Helper\ScenarioBuilder;


class SettingControllerBuilder extends AbstractScenarioBuilder
{
    public function build()
    {
        parent::build(); // TODO: Change the autogenerated stub
    }
}